import Image from 'next/image'

const clients = [
  {
    Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/adidas.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/agusti-torello-mata.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/alfaparf.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/audi.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/bacardi.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/carrefour.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/cebado.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/cinesa.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/ciruit-catalunya.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/clarion.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/Danone.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/dulcesol.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/elpozo.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/farina.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/ferrari.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/freeman.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/freixenet.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/GinMG.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/isabel.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/jamon-teruel.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/kellogs.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/lakme.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/llongueras.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/loreal.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/lucky.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/mango.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/marco_aldany.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/massimo.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/me-by-melia.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/melia.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/mercedes.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/mga-grupo.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/montibello.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/nal3comunicacio.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/noel.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/norma.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/oleoestepa.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/onecowork.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/oysho.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/parc-valles.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/PhilipMorris.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/porsche-300x188.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/porsche.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/privalia.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/rally-car.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/revlon.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/sasson.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/schwarkopf.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/seat.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/seatra.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/sorisa.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/suzuki.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/telefonica.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/thuya.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/tony-guy.png?raw=true',
  },
  {
  Image:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/vice.png?raw=true',
},

]

export default function Example() {
  return (
    <div className="bg-white">
      <div className="mx-auto py-12 px-4 max-w-7xl sm:px-6 lg:px-8 lg:py-24">
        <div className="space-y-12 lg:grid lg:grid-cols-3 lg:gap-8 lg:space-y-0">
          <div className="lg:col-span-3">
            <ul
              role="list"
              className="space-y-12 sm:grid sm:grid-cols-3 sm:gap-x-6 sm:gap-y-12 sm:space-y-0 lg:gap-x-8"
            >
              {clients.map((clients) => (
                <li key={clients.Image}>
                  <div className="space-y-4">
                    <div className="aspect-w-3">
                    <Image
                      className="object-cover shadow-lg rounded-lg"
                      src={clients.Image}
                      alt={clients.Image}
                      width={720}
                      height={1080}
                    />
                    </div>
                    <div className="text-lg text-black leading-6 font-medium space-y-1">
                      <h3>{clients.Image}</h3>
                    </div>
                    <div className="text-lg">
                      <p className="text-black">{clients.Image}</p>
                    </div>
                    <ul role="list" className="flex space-x-5">
                    </ul>
                  </div>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </div>
  )
}
